### ISSUE TITLE
Link tools: once formatted, give the user the option to browse the json they entered

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/holistic-toolbox#39]
We can add a link to the taskbar of json-formatter that sends the entered JSON as a query string. 

We'll need to add the functionality to read json from a url query string to the json-browser for this to work.

It could be an idea to make this two way, and add a link to json-browser than send you to json-formatter also.

_This makes me think we might also want to rework json-formatter as json-editor 🤔 - maybe another time_

## Roadmap
- [x] add query string handling to json-browser so that json can be loaded via a url
    _#65_
- [x] add 'get shareable link' that copies the url with the current json as a query string to json-browser
    _#65_
- [x] add link to 'browse-json' to the json-formatter
    _#66_
- [x] update json-browser readme
    _#65_
- [x] update json-formatter readme
    _#66_

**Comment by michaelfitzhavey** [comment]
PR #65 exists to add the necessary changes to json-browser. I'll update json-formatter after this has been deployed.

**Comment by michaelfitzhavey** [comment]
All deployed 💯
